
export const schemaSQL = `-- Create a table for public profiles
create table profiles (
  id uuid not null references auth.users on delete cascade,
  updated_at timestamp with time zone,
  name text,
  avatar_url text,
  height numeric,
  weight numeric,
  age int,
  gender text,
  bio text,
  goals text[],
  title text,
  stats jsonb default '{}'::jsonb,

  primary key (id)
);

alter table profiles
  enable row level security;

create policy "Public profiles are viewable by everyone." on profiles
  for select using (true);

create policy "Users can insert their own profile." on profiles
  for insert with check (auth.uid() = id);

create policy "Users can update own profile." on profiles
  for update using (auth.uid() = id);

-- Create a table for gamification stats
create table gamification (
  user_id uuid not null primary key references auth.users on delete cascade,
  level int default 1,
  rank text default 'E-Rank',
  streak_days int default 0,
  progress_to_next bigint default 0, -- Total XP
  last_activity timestamp with time zone
);

alter table gamification
  enable row level security;
  
create policy "Users can manage their own gamification stats." on gamification
  for all using (auth.uid() = user_id);

-- Create a table for tasks
create table tasks (
  id text not null primary key,
  user_id uuid not null references auth.users on delete cascade,
  project_id text,
  title text not null,
  category text not null,
  complexity text not null,
  xp int not null,
  done boolean default false,
  note text,
  tags text[],
  details jsonb, -- for subtasks, due date
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone
);

alter table tasks
  enable row level security;
  
create policy "Users can manage their own tasks." on tasks
  for all using (auth.uid() = user_id);

-- Create a table for projects
create table projects (
    id text not null primary key,
    user_id uuid not null references auth.users on delete cascade,
    title text not null,
    description text,
    status text default 'Active',
    deadline date,
    tags text[],
    xp_bonus int default 0,
    milestones jsonb default '[]'::jsonb,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone
);

alter table projects
  enable row level security;

create policy "Users can manage their own projects." on projects
  for all using (auth.uid() = user_id);


-- Create a table for skill levels (part of deep stats)
create table skill_levels (
    id text not null primary key,
    user_id uuid not null references auth.users on delete cascade,
    domain text not null,
    name text not null,
    level int default 1,
    mastery int default 0,
    rank text default 'E',
    techniques jsonb default '[]'::jsonb,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone
);

alter table skill_levels
  enable row level security;
  
create policy "Users can manage their own skills." on skill_levels
  for all using (auth.uid() = user_id);

-- Create a table for business ventures (part of deep stats)
create table business_fields (
    id text not null primary key,
    user_id uuid not null references auth.users on delete cascade,
    name text not null,
    type text not null,
    revenue numeric default 0,
    status text default 'Idea',
    efficiency int default 0,
    sub_ventures jsonb default '[]'::jsonb,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone
);

alter table business_fields
  enable row level security;
  
create policy "Users can manage their own business ventures." on business_fields
  for all using (auth.uid() = user_id);


-- Create a table for fitness metrics (part of deep stats)
create table fitness_metrics (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users on delete cascade,
    date date not null default now(),
    strength jsonb,
    muscle jsonb,
    aesthetics jsonb,
    body_fat numeric,
    unique(user_id, date)
);

alter table fitness_metrics
  enable row level security;

create policy "Users can manage their own fitness metrics." on fitness_metrics
  for all using (auth.uid() = user_id);

-- Create a table for other deep stats snapshots
create table user_snapshots (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users on delete cascade,
    category text not null, -- e.g., 'Finance', 'Wellness'
    data jsonb,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table user_snapshots
  enable row level security;
  
create policy "Users can manage their own snapshots." on user_snapshots
  for all using (auth.uid() = user_id);


-- Set up Storage!
insert into storage.buckets (id, name, public)
values ('avatars', 'avatars', true);

create policy "Avatar images are publicly accessible."
  on storage.objects for select
  using ( bucket_id = 'avatars' );

create policy "Anyone can upload an avatar."
  on storage.objects for insert
  with check ( bucket_id = 'avatars' );

create policy "Anyone can update their own avatar."
  on storage.objects for update
  using ( auth.uid() = owner )
  with check ( bucket_id = 'avatars' );
`;